name = "StatGeochemBase"
uuid = "61e559cd-58b4-4257-8528-26bb26ff2b9a"
authors = ["C. Brenhin Keller"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
